### ISSUE TITLE
List of bugs & todo and possible improvements

### ISSUE THREAD

**Issue by Zeinok** [YuntechNet/YunNet-Backend#2]
# Major
- [ ] MAC isn't swapped after swapping bed owners.
https://github.com/YuntechNet/YunNet-Backend/blob/56c9ec3e1cf6876eb4c419d5fccf7535c146087c/api/management/bed_change.py#L50-L70
- [ ] UNIQUE exception is not handled.
https://github.com/YuntechNet/YunNet-Backend/blob/56c9ec3e1cf6876eb4c419d5fccf7535c146087c/api/user/mac.py#L77
https://github.com/YuntechNet/YunNet-Backend/blob/56c9ec3e1cf6876eb4c419d5fccf7535c146087c/Query/mac.py#L37-L56
# Minor & To-do
- [ ] Remove legacy `aiohttp` instance under `app` in `backend.py` and move to `Base.aiohttpSession`.
https://github.com/YuntechNet/YunNet-Backend/blob/56c9ec3e1cf6876eb4c419d5fccf7535c146087c/backend.py#L51
- [ ] `BackgroundJobs/bulk_import.py` is untested.
# Missing API endpoints
- [ ] User creation/deletion
- [] Role(refered as group in source code) assignment/revoke
# Possible Improvements
- [ ] Move bed change log and action log to MySQL and use MongoDB entirely just for API access details.
- [ ] Merge `/api/management/` route to `/api/`.
